apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-nginx003-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
kind: Service
metadata:
  name: aks-nginx003-service-port-8000
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: LoadBalancer
       
